config/routes.rb
Rails.application.routes.draw do

  root 'translators#index'

  resources :translators, :only => [:show]
  post :translate, to: 'translators#translate'
  get :translation, to: 'translators#translation'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/translators_controller.rb
class TranslatorsController < ApplicationController
	before_action :get_token, :only => [:index]

	def index
		if params[:output]
			@output = params[:output]
		end

	end

	def show
	end

	def translate
		translator = BingTranslator.new(ENV['Microsoft_id'], ENV['Microsoft_secret'], false, ENV['Azure_account_key'])
		@text = translator_params[:libretto].squish.split(/\s*(?<=[.,;?])\s*|\s{2,}|[\r\n]+/x)
		# # @output = EasyTranslate.translate(@text, :to => :en, :key => ENV['Google_API_Key']).split(/\s*(?<=[.,;?])\s*|\s{2,}|[\r\n]+/x)
		@output = translator.translate_array2(@text, from: 'it', to: 'en')
		# .split(/\s*(?<=[.,;?])\s*|\s{2,}|[\r\n]+/x)
		# response = RestClient.post(
		# 	"http://api.microsofttranslator.com/V2/Http.svc/GetTranslations",
		# 		:Authorization => "Bearer #{@token['access_token']}",
		# 		:params => {
		# 			"text" => @text,
		# 			"from" => 'it',
		# 			"to" => 'en',
		# 			}
		# 	)
		# @output = response
		# .squish.split(/\s*(?<=[.,;?])\s*|\s{2,}|[\r\n]+/x)
		@text_array = @text
		# .squish.split(/\s*(?<=[.,;?])\s*|\s{2,}|[\r\n]+/x)
		respond_to do |format|
			format.js
		end
	end

	def translation

	end

	private

	def translator_params
		params.require(:translator).permit(:libretto)
	end

	def get_token
		begin
	    translator = BingTranslator.new(ENV['Microsoft_id'], ENV['Microsoft_secret'], false, ENV['Azure_account_key'])
	    @token = translator.get_access_token
	    @token[:status] = 'success'
	  rescue Exception => exception
	    YourApp.error_logger.error("Bing Translator: \"#{exception.message}\"")
	    @token = { :status => exception.message }
	  end

	  @token
	end

	# def translate_params(access_token, text, from, to, content_type = nil)
	# 	param_hash = {
	# 		:Authorization => "Bearer #{access_token}",
	# 		"text" => text,
	# 		"from" => from,
	# 		"to" => to,
	# 		"content_type" => content_type
	# 	}
	# 	param_hash
	# end

	def parse_xml(xml)
      xml_doc = Nokogiri::XML(xml)
      xml_doc.xpath("/").text
    end

	def set_google_api
		EasyTranslate.api_key = ENV['Google_API_KEY']
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translators_helper.rb
module TranslatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Librettist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = 'container'>
	<% if notice.present? %>
	<p class="alert alert-info"><%= notice %></p>
	<% end %>

	<% if alert.present? || flash[:error] %>
	<p class="alert alert-danger"><%= alert || flash[:error] %></p>
	<% end %>

	<%= yield %>
</div>

</body>
</html>

app/views/translators/_literal.html.erb
<% @text_array.each_with_index do |sentence, index| %>

	<% @output[index][1].split(" ").each do |alignment| %>
		<% coord = alignment.split(/\s*[:-]\s*/) %>

		<div class = 'word_block'>
			<div class = 'text_row'>
				<%= sentence[coord[0].to_i..coord[1].to_i] %>
			</div>
			<div class = 'output_row'>
				<%= @output[index][0][coord[2].to_i..coord[3].to_i] %>
			</div>
		</div>
	<% end %>
	<br />
<% end %>

app/views/translators/index.html.erb
<div class="spacer-50"></div>
<h1>Librettist</h1>

<div class="col-xs-12 col-sm-6">
	<%= simple_form_for :translator, url: translate_path, remote: true do |f| %>
		<%= f.input :libretto, as: :text %>
		<%= f.button :submit, "Translate", :id => 'translate_btn' %>
	<% end %>
</div>

<div class="col-xs-12 col-sm-6">
	<div id = 'textOutput'>
		<%= @output if @output.present? %>
	</div>
</div>

<script>

$(document).ready(function() {

			
		
})
</script>

app/views/translators/translate.js.erb
$('#textOutput').html('<%= j render "literal" %>');